#!/usr/bin/env bash

# Copyright (c) 2021-2025 community-scripts ORG
# Author: Generated by template generator
# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE

# Set up colors and formatting
YW=$(echo "\033[33m")
BL=$(echo "\033[36m")
RD=$(echo "\033[01;31m")
BGN=$(echo "\033[4;92m")
GN=$(echo "\033[1;92m")
DGN=$(echo "\033[32m")
CL=$(echo "\033[m")
BFR="\\r\\033[K"
HOLD="-"
CM="${GN}✓${CL}"

function msg_info() {
    local msg="$1"
    echo -ne " ${HOLD} ${YW}${msg}..."
}

function msg_ok() {
    local msg="$1"
    echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}

function msg_error() {
    local msg="$1"
    echo -e "${BFR} ${RD}✗ ${msg}${CL}"
}

# Header
clear
cat <<"EOF"
   ____  _     _     _     _    __  __  ___  _   _ 
  / ___|| |   (_)___| |__ | |  |  \/  |/ _ \| \ | |
  \___ \| |   | / __| '_ \| |  | |\/| | | | |  \| |
   ___) | |___| \__ \ | | | |  | |  | | |_| | |\  |
  |____/|_____|_|___/_| |_|_|  |_|  |_|\___/|_| \_|
                                                    
EOF

echo -e "${BL}This script will help you switch between development and production modes for repository paths.${CL}\n"

# Get current mode
if grep -q "community-scripts/ProxmoxVE/main" misc/build.func; then
    CURRENT_MODE="production"
else
    CURRENT_MODE="development"
fi

echo -e "Current mode: ${BGN}${CURRENT_MODE}${CL}\n"

# Get mode selection
echo "Select mode:"
echo "1) Development (for testing in your fork)"
echo "2) Production (for submitting PR)"
read -p "Enter choice (1/2): " MODE_CHOICE

case $MODE_CHOICE in
    1)
        if [[ "$CURRENT_MODE" == "development" ]]; then
            echo -e "\n${YW}Already in development mode.${CL}"
            exit 0
        fi
        
        # Get development details
        read -p "Enter your GitHub username: " GITHUB_USERNAME
        read -p "Enter your repository name (default: ProxmoxVE): " REPO_NAME
        REPO_NAME=${REPO_NAME:-ProxmoxVE}
        read -p "Enter your branch name: " BRANCH_NAME
        
        # Update paths in build.func
        msg_info "Updating build.func"
        sed -i "s|https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main|https://raw.githubusercontent.com/${GITHUB_USERNAME}/${REPO_NAME}/refs/heads/${BRANCH_NAME}|g" misc/build.func
        msg_ok "Updated build.func"
        
        # Update paths in install.func
        msg_info "Updating install.func"
        sed -i "s|https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main|https://raw.githubusercontent.com/${GITHUB_USERNAME}/${REPO_NAME}/refs/heads/${BRANCH_NAME}|g" misc/install.func
        msg_ok "Updated install.func"
        
        # Update paths in all ct/*.sh files
        msg_info "Updating container scripts"
        for file in ct/*.sh; do
            if [ -f "$file" ]; then
                sed -i "s|https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main|https://raw.githubusercontent.com/${GITHUB_USERNAME}/${REPO_NAME}/refs/heads/${BRANCH_NAME}|g" "$file"
            fi
        done
        msg_ok "Updated container scripts"
        
        echo -e "\n${GN}Successfully switched to development mode!${CL}"
        echo -e "Using repository: ${BL}${GITHUB_USERNAME}/${REPO_NAME}${CL}"
        echo -e "Branch: ${BL}${BRANCH_NAME}${CL}"
        ;;
        
    2)
        if [[ "$CURRENT_MODE" == "production" ]]; then
            echo -e "\n${YW}Already in production mode.${CL}"
            exit 0
        fi
        
        # Confirm before switching to production
        echo -e "\n${YW}Warning: This will change all paths back to the community-scripts repository.${CL}"
        read -p "Are you sure you want to continue? (y/N): " CONFIRM
        if [[ ${CONFIRM^^} != "Y" ]]; then
            echo -e "\n${RD}Operation cancelled.${CL}"
            exit 0
        fi
        
        # Update paths in build.func
        msg_info "Updating build.func"
        sed -i "s|https://raw.githubusercontent.com/.*/refs/heads/.*|https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main|g" misc/build.func
        msg_ok "Updated build.func"
        
        # Update paths in install.func
        msg_info "Updating install.func"
        sed -i "s|https://raw.githubusercontent.com/.*/refs/heads/.*|https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main|g" misc/install.func
        msg_ok "Updated install.func"
        
        # Update paths in all ct/*.sh files
        msg_info "Updating container scripts"
        for file in ct/*.sh; do
            if [ -f "$file" ]; then
                sed -i "s|https://raw.githubusercontent.com/.*/refs/heads/.*|https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main|g" "$file"
            fi
        done
        msg_ok "Updated container scripts"
        
        echo -e "\n${GN}Successfully switched to production mode!${CL}"
        echo -e "Using repository: ${BL}community-scripts/ProxmoxVE${CL}"
        echo -e "Branch: ${BL}main${CL}"
        ;;
        
    *)
        echo -e "\n${RD}Invalid choice. Exiting...${CL}"
        exit 1
        ;;
esac

echo -e "\n${BL}Remember to commit your changes before submitting a pull request!${CL}" 